google-chrome-stable:
  - run wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - run echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
  - apt-get

git:
  - apt-get

atom:
  - repository: ppa:webupd8team/atom
  - apt-get

python3-setuptools:
  - apt-get

pip35:
  - install python3-setuptools
  - sudo easy_install3 pip

terminator:
  - repository: ppa:gnome-terminator/nightly
  - apt-get

default-jdk:
  - apt-get

nodejs:
  - apt-get

npm:
  - apt-get

stable-node:
  - install:
    - npm
    - nodejs
  - sudo npm cache clean -f
  - sudo npm install -g n
  - sudo n stable

hipchat:
  - wget https://atlassian.artifactoryonline.com/atlassian/hipchat-apt-client/pool/HipChat4-4.0.1517-Linux.deb
  - sudo dpkg -i HipChat4-4.0.1517-Linux.deb
  - rm -f HipChat4-4.0.1517-Linux.deb

sublime-text:
  - wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
  - echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
  - apt-get

pycharm:
  - jetbrains: PCP

webstorm:
  - jetbrains: WS

idea:
  - jetbrains: IIU

datagrip:
  - jetbrains: DG

clion:
  - jetbrains: CL

python-tk:
  # Necessary to run a whole bunch of python stuff
  - apt-get

python3-dev:
  # Necessary package for installing cython
  - apt-get

